server:
  port: 8088
  servlet:
    context-path: /introduction
  tomcat:
    #tomcat的URI编码
    uri-encoding: UTF-8
    #tomcat最大线程数，默认为200
    max-threads: 800
    #Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

#spring 配置
spring:
  #激活配置文件
  profiles:
    active:  @activatedProperties@
  #启动就初始化servlet
  mvc:
    #静态资源访问路径
    static-path-pattern: /**
    #静态资源路径配置
    static-locations: classpath:/static
    servlet:
      load-on-startup: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    druid:
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        #IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #禁用HTML页面上的“Reset All”功能
        reset-enable: "false"
        #登录名
        login-username: admin
         #登陆密码
        login-password: 123456

#mybatis配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  type-aliases-package: org.wangqian
  global-config:
    db-config:
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 打印sql日志
logging:
  level:
    org.wangqian: debug

