spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      datasource1:
        url: jdbc:mysql://59.110.64.133:3306/introduction?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      datasource2:
        url: jdbc:mysql://59.110.64.133:3306/introduction?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      datasource3:
        url: jdbc:mysql://59.110.64.133:3306/introduction?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
